### ISSUE TITLE
Quarkc 开发 collapse 组件源码

### ISSUE THREAD

**Issue by OSpoon** [OSpoon/lf-dnd-panel#1]
# Quarkc 开发 collapse 组件源码

## index.tsx

```typescript
import { QuarkElement, property, customElement, createRef } from "quarkc";
import style from "./index.less?inline";

export interface Props {
  open?: boolean;
  title: string;
}

@customElement({
  tag: "px-collapse",
  style,
})
class PxCollapse extends QuarkElement {
  @property({
    type: Boolean,
  })
  open = false;

  @property({
    type: String,
  })
  title = "";

  detailsEl: any = createRef();

  componentDidMount() {
    if (this.open) {
      const { current } = this.detailsEl;
      current.open = true;
    }
  }

  shouldComponentUpdate(
    propName: string,
    oldValue: string | boolean,
    newValue: string | boolean
  ): boolean {
    if (propName === "open" && oldValue !== newValue) {
      const { current } = this.detailsEl;
      current.open = newValue;
    }
    return true;
  }

  render() {
    return (
      <details ref={this.detailsEl}>
        <summary>
          <slot name="title">{this.title}</slot>
          <div className="icon">↓</div>
          <div className="line"></div>
        </summary>
        <div class="expander-content">
          <slot></slot>
        </div>
      </details>
    );
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "px-collapse": PxCollapse;
  }
}
```

## index.less

```css
details {
  background-color: #fff;
}

.icon {
  float: right;
}

details[open] .icon {
  transform: rotate(180deg);
}

summary {
  padding: 13px 26px;
  color: var(--callapse-title-color, #666);
  font-size: var(--callapse-title-fontsize, 14px);
  position: relative;
  cursor: pointer;
  transition: all 0.4s;
}

summary:first-of-type {
  list-style-type: none;
}

.collapse-icon {
  position: absolute;
  right: 26px;
  top: 15px;
}

.line {
  width: calc(100% - 52px);
  height: 1px;
  background: #ebedf0;
  position: absolute;
  bottom: 0;
}

.expander-content {
  color: var(--callapse-content-color, #666);
  font-size: var(--callapse-content-fontsize, 14px);
  line-height: 1.5;
  background-color: #fff;
  padding: 12px 28px;
}

:host([iconhide]) quark-icon-arrow-down {
  display: none;
}
```
